---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@c61e8107b080f72e25bfc41d3eef947dbfa66446 # v3.0.0
    permissions:
      contents: write
      pull-requests: write
